language: php

php:
  - '7.0'
  - '7.1'

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.travis.xml
  - vendor/bin/phpcs --standard=PSR2 src/ tests/

after_success:
  - travis_retry php vendor/bin/coveralls
